robotframework-robottools: more WIP
Weird build error:

nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
not an ELF executable
nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
ntching script interpreter paths
/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer: interpreter directive changed from "/usr/bin/env python" to "/nix/store/6l1bvljpy8gazlsw2aw9skwwp4pmvyxw-python-2.7.8/bin/python "
ix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
not an ELF executable
[q[ppatching script interpreter paths
/nixastore/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer: interpreter directive changed from "/usr/bin/env python" to "/nix/store/6l1bvljpy8gazlsw2aw9skwwp4pmvyxw-python-2.7.8/bin/python "
nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
lder for `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed with exit code 1
error: build of `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed

nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
not an ELF executable
[q[ppatching script interpreter paths
/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer: interpreter directive changed from "/usr/bin/env python" to "/nix/store/6l1bvljpy8gazlsw2aw9skwwp4pmvyxw-python-2.7.8/bin/python "
[q/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
wrapping `/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer'...
/nix/store/fivgvy4aciijxgwy11j7i2gc7jslh4yf-hook/nix-support/setup-hook: line 67: /nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/lib/python2.7/site-packages/python2.7-robotframework-robottools-20140228-nix-python-propagated-native-build-inputs.pth: No such file or directory
[q[qbuilder for `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed with exit code 1
error: build of `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed

not an ELF executable
[q[ppatching script interpreter paths
/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer: interpreter directive changed from "/usr/bin/env python" to "/nix/store/6l1bvljpy8gazlsw2aw9skwwp4pmvyxw-python-2.7.8/bin/python "
[q/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
wrapping `/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer'...
/nix/store/fivgvy4aciijxgwy11j7i2gc7jslh4yf-hook/nix-support/setup-hook: line 67: /nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/lib/python2.7/site-packages/python2.7-robotframework-robottools-20140228-nix-python-propagated-native-build-inputs.pth: No such file or directory
[q[qbuilder for `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed with exit code 1
error: build of `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed

[q/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
wrapping `/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer'...
/nix/store/fivgvy4aciijxgwy11j7i2gc7jslh4yf-hook/nix-support/setup-hook: line 67: /nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/lib/python2.7/site-packages/python2.7-robotframework-robottools-20140228-nix-python-propagated-native-build-inputs.pth: No such file or directory
[q[qbuilder for `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed with exit code 1
error: build of `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed

not an ELF executable
[q[ppatching script interpreter paths
/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer: interpreter directive changed from "/usr/bin/env python" to "/nix/store/6l1bvljpy8gazlsw2aw9skwwp4pmvyxw-python-2.7.8/bin/python "
[q/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer
wrapping `/nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/bin/fileviewer'...
/nix/store/fivgvy4aciijxgwy11j7i2gc7jslh4yf-hook/nix-support/setup-hook: line 67: /nix/store/l70nykd4jyqv7xb9acrg2bn8qqdqifqq-python2.7-robotframework-robottools-20140228/lib/python2.7/site-packages/python2.7-robotframework-robottools-20140228-nix-python-propagated-native-build-inputs.pth: No such file or directory
[q[qbuilder for `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed with exit code 1
error: build of `/nix/store/rl93iw7rp9c3k163jnzj1p7rn89cdq8d-python2.7-robotframework-robottools-20140228.drv' failed