WIP: Repetier-Host: new package (IT DOESN'T BUILD YET)
It doesn't find OpenTK:

Errors:

/tmp/nix-build-repetier-host-0.85.drv-1/git-export/src/RepetierHost/RepetierHost.sln
(default targets) ->
(Build target) ->
/tmp/nix-build-repetier-host-0.85.drv-1/git-export/src/RepetierHost/RepetierHost.csproj
(default targets) ->
/nix/store/d3xdkijxkcak0hcblgwjdwcms89hshvx-mono-2.11.4/lib/mono/3.5/Microsoft.CSharp.targets
(CoreCompile target) ->

        model/GCodeVisual.cs(21,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/GCodeVisual.cs(23,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/GCodeVisual.cs(24,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/PulseAnimation.cs(5,7): error CS0246: The type or
namespace name `OpenTK' could not be found. Are you missing an assembly
reference?
        model/PulseAnimation.cs(6,7): error CS0246: The type or
namespace name `OpenTK' could not be found. Are you missing an assembly
reference?
        model/STL.cs(21,7): error CS0246: The type or namespace name
`OpenTK' could not be found. Are you missing an assembly reference?
        model/STL.cs(22,7): error CS0246: The type or namespace name
`OpenTK' could not be found. Are you missing an assembly reference?
        model/ThreeDModel.cs(21,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/ThreeDModel.cs(22,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/ThreeDModel.cs(23,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/ThreeDView.cs(5,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/ThreeDView.cs(6,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        model/ThreeDView.cs(7,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/STLComposer.cs(27,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/ThreeDControl.cs(25,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/ThreeDControl.cs(26,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/ThreeDControl.cs(27,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/ThreeDSettings.cs(29,7): error CS0246: The type or
namespace name `OpenTK' could not be found. Are you missing an assembly
reference?
        view/utils/RHOpenGL.cs(5,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/utils/RHOpenGL.cs(6,7): error CS0246: The type or namespace
name `OpenTK' could not be found. Are you missing an assembly reference?
        view/utils/RHOpenGL.cs(13,29): error CS0246: The type or
namespace name `OpenTK' could not be found. Are you missing an assembly
reference?
        model/GCodeVisual.cs(36,16): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        model/GCodeVisual.cs(43,16): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        model/GCodeVisual.cs(44,16): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        model/GCodeVisual.cs(59,25): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        model/ThreeDModel.cs(153,24): error CS0246: The type or
namespace name `Vector3' could not be found. Are you missing an assembly
reference?
        model/STL.cs(32,16): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(33,16): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(75,16): error CS0246: The type or namespace name
`Matrix4' could not be found. Are you missing an assembly reference?
        model/STL.cs(188,25): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(217,39): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(231,40): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(401,42): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(415,40): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(415,51): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/STL.cs(464,17): error CS0246: The type or namespace name
`Vector3' could not be found. Are you missing an assembly reference?
        model/ThreeDView.cs(21,16): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        model/ThreeDView.cs(22,16): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        model/ThreeDView.cs(23,16): error CS0246: The type or namespace
name `Matrix4' could not be found. Are you missing an assembly
reference?
        view/STLComposer.cs(368,42): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        view/STLComposer.cs(382,40): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        view/STLComposer.cs(382,51): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        view/ThreeDControl.cs(44,9): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        view/ThreeDControl.cs(45,9): error CS0246: The type or namespace
name `Vector3' could not be found. Are you missing an assembly
reference?
        view/ThreeDControl.cs(747,17): error CS0246: The type or
namespace name `Matrix4' could not be found. Are you missing an assembly
reference?
        view/ThreeDSettings.cs(422,17): error CS0246: The type or
namespace name `Vector4' could not be found. Are you missing an assembly
reference?
        view/ThreeDSettings.cs(429,16): error CS0246: The type or
namespace name `Vector4' could not be found. Are you missing an assembly
reference?
        view/ThreeDSettings.cs(430,16): error CS0246: The type or
namespace name `Vector4' could not be found. Are you missing an assembly
reference?
        view/ThreeDSettings.cs(431,16): error CS0246: The type or
namespace name `Vector4' could not be found. Are you missing an assembly
reference?
        view/ThreeDSettings.cs(432,16): error CS0246: The type or
namespace name `Vector4' could not be found. Are you missing an assembly
reference?
        view/utils/RHOpenGL.cs(53,33): error CS0115:
`RepetierHost.view.utils.RHOpenGL.IsInputKey(System.Windows.Forms.Keys)'
is marked as an override but no suitable method found to override

         6 Warning(s)
         51 Error(s)
----

Repetier-Host is software for controlling RepRap style 3D-printer like
Mendel, Darwin or Prusa mendel. Works with most firmware types. It is
optimized to work with Repetier-Firmware Other working firmware is
Sprinter, Teacup, Marlin and all compatible firmwares.